name: ProductExplorer CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install SwiftLint
        run: brew install swiftLint
        
      - name: SwiftLint
        run: swiftlint lint --strict

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show available simulators
        run: xcrun simctl list devices available

      - name: Build
        run: |
          xcodebuild \
            -project ProductExplorer.xcodeproj \
            -scheme ProductExplorer \
            -sdk iphonesimulator \
            -configuration Debug \
            build

      - name: Test
        run: |
          xcodebuild \
            -project ProductExplorer.xcodeproj \
            -scheme ProductExplorer \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            test
            
      - name: Check Code Coverage
        run: |
          xcrun xccov view --report TestResults.xcresult > coverage.txt
          
          cat coverage.txt
          
          COVERAGE=$(grep -E "^[:space:]*ProductExplorer\.app:" coverage.txt | awk '{print $NF}' | tr -d '%')
          
          echo "Coverage: ${COVERAGE}%"
          
          MINIMUM=80
          
          if (( $(echo "$COVERAGE < $MINIMUM" | bc -l) )); then
            echo "❌ code coverage is bleow ${MINIMUM}%"
            exit 1
          fi
          
          echo "✅ Code coverage is ${COVERAGE}%"
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ProductExplorer-TestResults
          path: TestResults.results
